"""Initial database

Revision ID: 18ef11108042
Revises: 
Create Date: 2023-04-12 00:22:45.865035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ef11108042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('comentarios', sa.String(length=1000), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=128), nullable=False),
    sa.Column('correo', sa.String(length=256), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Estudiante', 'Profesor', 'PAS', 'Externo'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.CheckConstraint('length(telefono) == 9', name='check_telefono_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni', name='uq_dni')
    )
    op.create_table('informe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretario', sa.String(length=256), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('escuela', 'comision'), nullable=False),
    sa.Column('dni_miembro', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dni_miembro'], ['miembro.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembros_comisiones',
    sa.Column('dni_miembro', sa.String(length=20), nullable=False),
    sa.Column('id_comision', sa.Integer(), nullable=False),
    sa.Column('fecha_incorporacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_baja', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dni_miembro'], ['miembro.dni'], ),
    sa.ForeignKeyConstraint(['id_comision'], ['comision.id'], ),
    sa.PrimaryKeyConstraint('dni_miembro', 'id_comision')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miembros_comisiones')
    op.drop_table('informe')
    op.drop_table('miembro')
    op.drop_table('comision')
    op.drop_table('administrativo')
    # ### end Alembic commands ###
