"""Cambio de datetime por date para representar las fechas

Revision ID: 79215ba1060f
Revises: d3c01e2aaf62
Create Date: 2023-05-23 23:42:50.468651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79215ba1060f'
down_revision = 'd3c01e2aaf62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comision', schema=None) as batch_op:
        batch_op.alter_column('fecha_apertura',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('fecha_cierre',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('miembros_comisiones', schema=None) as batch_op:
        batch_op.alter_column('fecha_incorporacion',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('fecha_baja',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros_comisiones', schema=None) as batch_op:
        batch_op.alter_column('fecha_baja',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('fecha_incorporacion',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('comision', schema=None) as batch_op:
        batch_op.alter_column('fecha_cierre',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('fecha_apertura',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
