"""Añadido campos nombre y apellidos a Administrativo

Revision ID: a3ccc52e4136
Revises: 56fcecd9e377
Create Date: 2023-04-27 10:04:27.674899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ccc52e4136'
down_revision = '56fcecd9e377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrativo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrativo', schema=None) as batch_op:
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
