"""Modificados campos telefono y correo de Miembro como opcionales

Revision ID: d17d4c7e770e
Revises: a3ccc52e4136
Create Date: 2023-05-10 13:32:19.897092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17d4c7e770e'
down_revision = 'a3ccc52e4136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.TEXT(),
               type_=sa.Enum('escuela', 'comision'),
               existing_nullable=False)

    with op.batch_alter_table('miembro', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembro', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('informe', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('escuela', 'comision'),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
